image: python:3.6

stages:
 - test

before_script:
  - apt-get update --yes
  - apt-get install --yes build-essential cmake libfmt-dev pybind11-dev
  - pip3 install pytest pytest-cov
  - pip3 install .
  - pip3 show b_asic

run tests:
  stage: test
  script:
    - pytest test