stages:
 - test
 - test-gui

.run-test:
  stage: test
  script:
    - apt-get update --yes
    - apt-get install --yes build-essential cmake libfmt-dev pybind11-dev
    - python -m pip install --upgrade pip
    - python --version
    - pip install pytest pytest-cov
    - pip install .
    - pip show b_asic
    - pytest --cov=b_asic --cov-report xml:cov.xml --cov-report term test
  artifacts:
      reports:
        coverage_report:
          coverage_format: cobertura
          path: cov.xml

run-test-3.6:
  image: python:3.6
  extends: ".run-test"

run-test-3.7:
  image: python:3.7
  extends: ".run-test"

run-test-3.8:
  image: python:3.8
  extends: ".run-test"

run-test-3.9:
  image: python:3.9
  extends: ".run-test"

run-test-3.10:
  image: python:3.10
  extends: ".run-test"

run-gui-test:
  image: ubuntu-latest
  stage: test-gui
  script:
      - apt-get update --yes
      - apt-get install --yes build-essential cmake libfmt-dev pybind11-dev \
         xvfb
      - apt-get install --yes python3 python3-pip
      - apt-get install --yes python3-pyqt5
      - python -m pip install --upgrade pip
      - python --version
      - pip install pytest pytest-cov pytest-xvfb pytest-qt
      - pip install .
      - pip show b_asic
      - pytest --cov=b_asic --cov-report xml:cov.xml --cov-report term test
