[project]
name = "b-asic"
description = "Better ASIC Toolbox"
readme = "README.md"
maintainers = [{ name = "Oscar Gustafsson", email = "oscar.gustafsson@liu.se" }]
license = { file = "LICENSE" }
requires-python = ">=3.8"
dependencies = [
  "numpy",
  "qtpy",
  "graphviz>=0.19",
  "matplotlib",
  "setuptools_scm[toml]>=6.2",
  "networkx",
  "qtawesome"
]
classifiers = [
  "Intended Audience :: Education",
  "Intended Audience :: Science/Research",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: C++",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Topic :: Scientific/Engineering :: Electronic Design Automation (EDA)",
  "Development Status :: 3 - Alpha",
]
dynamic = ["version", "authors"]

[tool.setuptools]
zip-safe = false

[tool.setuptools.packages.find]
include = ["b_asic*"]

[build-system]
requires = [
  "setuptools>=45",
  "setuptools_scm[toml]>=6.2",
  "wheel",
  "oldest-supported-numpy"
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "b_asic/_version.py"
version_scheme = "release-branch-semver"
local_scheme = "node-and-date"
fallback_version = "0.0+UNKNOWN"

[project.urls]
homepage = "https://gitlab.liu.se/da/B-ASIC"
documentation = "https://da.gitlab-pages.liu.se/B-ASIC/"

[tool.black]
skip-string-normalization = true
preview = true
line-length = 88
exclude = "(test/test_gui/*|b_asic/scheduler_gui/ui_main_window.py)"

[tool.isort]
profile = "black"
line_length = 88
src_paths = ["b_asic", "test"]
skip = ["test/test_gui", "b_asic/scheduler_gui/ui_main_window.py"]

[tool.mypy]
packages = ["b_asic", "test"]
no_site_packages = true
ignore_missing_imports = true

[tool.coverage.report]
precision = 2

[tool.ruff]
ignore = ["F403"]

[tool.typos]
default.extend-identifiers = { addd0 = "addd0" }
