--
-- This code was automatically generated by the B-ASIC toolbox.
-- Code generation timestamp: (2025-08-05 10:58:11.318732)
-- B-ASIC short commit hash: 2129bde3
-- URL: https://gitlab.liu.se/da/B-ASIC
--

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity addsub0 is
    generic (
        WL_INTERNAL_INT : integer;
        WL_INTERNAL_FRAC : integer;
        WL_INPUT_INT : integer;
        WL_INPUT_FRAC : integer;
        WL_OUTPUT_INT : integer;
        WL_OUTPUT_FRAC : integer;
        WL_STATE : integer
    );
    port (
        clk : in std_logic;
        rst : in std_logic;
        schedule_cnt : in unsigned(WL_STATE-1 downto 0);
        p_0_in : in std_logic_vector(WL_INTERNAL_INT+WL_INTERNAL_FRAC-1 downto 0);
        p_1_in : in std_logic_vector(WL_INTERNAL_INT+WL_INTERNAL_FRAC-1 downto 0);
        p_0_out : out std_logic_vector(WL_INTERNAL_INT+WL_INTERNAL_FRAC-1 downto 0)
    );
end entity addsub0;

architecture rtl of addsub0 is
    signal re_op_a, re_op_b, im_op_a, im_op_b : signed(15 downto 0);
    signal re_res, im_res : signed(15 downto 0);
    signal is_add : std_logic;
begin
    process(clk)
    begin
        if rising_edge(clk) then
            if rst = '1' then
                re_op_a <= (others => '0');
                re_op_b <= (others => '0');
                im_op_a <= (others => '0');
                im_op_b <= (others => '0');
            else
                re_op_a <= signed(p_0_in(31 downto 16));
                re_op_b <= signed(p_1_in(31 downto 16));
                im_op_a <= signed(p_0_in(15 downto 0));
                im_op_b <= signed(p_1_in(15 downto 0));
            end if;
        end if;
    end process;

    is_add <= '1';

    re_res <= re_op_a + re_op_b when is_add = '1' else re_op_a - re_op_b;
    im_res <= im_op_a + im_op_b when is_add = '1' else im_op_a - im_op_b;

    p_0_out <= std_logic_vector(re_res) & std_logic_vector(im_res);

end architecture rtl;
