--
-- This code was automatically generated by the B-ASIC toolbox.
-- Code generation timestamp: (2025-07-21 13:25:54.609380)
-- B-ASIC short commit hash: 9ca7e25b
-- URL: https://gitlab.liu.se/da/B-ASIC
--

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity adder is
    generic(
        -- Data word length
        WL : integer := 8;
        -- Schedule counter length
        SCHEDULE_CNT_LEN : integer := 3
    );
    port(
        -- Clock and synchronous reset signals
        clk : in std_logic;
        rst : in std_logic;

        -- State counter
        schedule_cnt : in unsigned(SCHEDULE_CNT_LEN-1 downto 0);

        -- PE port I/O
        p_0_in : in std_logic_vector(WL-1 downto 0);

        p_1_in : in std_logic_vector(WL-1 downto 0);

        p_0_out : out std_logic_vector(WL-1 downto 0)
    );
end entity adder;

architecture rtl of adder is
    signal op_a, op_b : unsigned(WL-1 downto 0);
begin
    -- WRITE CODE HERE
    process(clk)
    begin
        if rising_edge(clk) then
            if rst = '1' then
                op_a <= (others => '0');
                op_b <= (others => '0');
            else
                op_a <= unsigned(p_0_in);
                op_b <= unsigned(p_1_in);
            end if;
        end if;
    end process;

    p_0_out <= std_logic_vector(op_a + op_b);

end architecture rtl;
